sudo: required  
dist: trusty
language: node_js
node_js:
  - "6.9"
os:
  - linux
rvm:
  - 2.2.0
addons:
  chrome: stable
branches:
  only:
    - master
cache:
  bundler: true
  directories:
    - ./node_modules/
stages:
  - cache
  - tests
  - name: deploy-master
    if: branch = master AND type = push
# before_install:
#   # start your web application and listen on `localhost`
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
# install:
#   - npm i -g npm@5.7.1
#   - npm ci
jobs:
  include:
    - stage: cache
      script: echo "Cache node_modules ..."
    - stage: tests
      before_script:
        - rm -rf ./coverage
        # code climate
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: 
        - export CHROME_BIN=chromium-browser
        # test with coverage
        - xvfb-run -a npm run test:coverage -- --no-progress --single-run true --watch false --browsers ChromeHeadless
      after_script:
        # coveralls
        - cat ./coverage/lcov.info | coveralls
        # codacy
        - cat ./coverage/lcov.info | codacy-coverage --language typescript
        # code climate
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: tests
      script:
        # e2e tests
        - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
    - stage: deploy-master
      script: 
        - echo "Deploying prod to azure ..."
        - npm run build:prod
      deploy:
        provider: azure_web_apps
        skip_cleanup: true
        site: at-st-app
        slot: at-st-app-staging
        on: master










